// Script de População de Dados (Seed) para o Supabase
// Execução: node seed_supabase.js

const supabaseUrl = 'https://ctuhwdlfqeawfdhmpmbw.supabase.co';
const serviceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0dWh3ZGxmcWVhd2ZkaG1wbWJ3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTA1MDkwOSwiZXhwIjoyMDk2NjI2OTA5fQ.P1bnZF3VxGXhQmHqv6dxL0-yTC_ZnX5rweIY8a4hoFo';

const QUESTIONS = [
  {id:1,cat:"legislacao",text:"Qual é a velocidade máxima permitida em vias urbanas (padrão)?",opts:["40 km/h","60 km/h","80 km/h","100 km/h"],ans:1,exp:"Em vias urbanas o CTB define 60 km/h como padrão, salvo indicação de placa diferente."},
  {id:2,cat:"legislacao",text:"De acordo com o CTB, o que configura 'estacionamento' de veículo?",opts:["Parada superior a 5 minutes","Imobilização voluntária por tempo superior ao necessário para embarque/desembarque","Parada por tempo indefinido em faixa exclusiva","Qualquer parada do veículo na via"],ans:1,exp:"O CTB define estacionamento como imobilização por tempo superior ao necessário para embarque/desembarque de passageiros ou carga/descarga de mercadorias."},
  {id:3,cat:"legislacao",text:"Qual documento NÃO é obrigatório portar ao dirigir um veículo no Brasil?",opts:["CNH","CRLV","Documento de identidade pessoal","Comprovante de pagamento do IPVA"],ans:3,exp:"O comprovante de pagamento do IPVA não é obrigatório para portar ao dirigir. Os obrigatórios são CNH, CRLV e documento de identidade."},
  {id:4,cat:"legislacao",text:"Em caso de acidente com vítima, o condutor que fugir do local poderá ter sua CNH:",opts:["Suspensa por 30 dias","Cassada","Suspensa por 1 ano","Apenas multado"],ans:1,exp:"Abandonar o local de acidente com vítima é infração gravíssima que pode levar à cassação da CNH."},
  {id:5,cat:"legislacao",text:"O que é a faixa de pedestre elevada (lombo faixa)?",opts:["Uma área de estacionamento exclusivo","Dispositivo para redução de velocidade e travessia de pedestre","Sinal de advertência pintado no chão","Faixa exclusiva para ônibus"],ans:1,exp:"A faixa de pedestre elevada combina a função de lombada eletrônica com a proteção ao pedestre na travessia."},
  {id:6,cat:"legislacao",text:"Qual a penalidade para quem dirigir com CNH vencida há mais de 30 dias?",opts:["Infração leve","Infração média","Infração grave","Infração gravíssima"],ans:2,exp:"Dirigir com CNH vencida há mais de 30 dias é infração grave, sujeita a multa e retenção do veículo."},
  {id:7,cat:"legislacao",text:"A preferência de passagem em cruzamentos não sinalizados pertence a:",opts:["Quem chegar primeiro","Veículo que vem pela direita","Veículo maior","Motocicleta"],ans:1,exp:"Em cruzamentos não sinalizados, tem preferência quem vem pela direita."},
  {id:8,cat:"legislacao",text:"Quantos pontos acumulados na CNH em 12 meses levam à suspensão?",opts:["15 pontos","20 pontos","25 pontos","30 pontos"],ans:1,exp:"A acumulação de 20 pontos in 12 meses causa a suspensão da CNH (salvo se o condutor tiver apenas infrações leves e médias, que permite até 40 pontos)."},
  {id:9,cat:"legislacao",text:"Na rodovia, qual é a faixa de maior velocidade?",opts:["A faixa da direita","A faixa do meio","A faixa da esquerda","Todas têm a mesma velocidade"],ans:2,exp:"A faixa da esquerda é para ultrapassagem e veículos mais rápidos. A faixa da direita é a de tráfego normal."},
  {id:10,cat:"legislacao",text:"Qual a distância mínima segura do veículo da frente recomendada pelo CTB?",opts:["5 metros","10 metros","15 metros","A distância necessária para parada segura"],ans:3,exp:"O CTB não define uma distância fixa, mas sim que deve ser a distância necessária para parar com segurança em caso de freada brusca do veículo da frente."},
  {id:11,cat:"legislacao",text:"É obrigatório o uso do cinto de segurança:",opts:["Apenas em vias expressas","Apenas para o motorista","Para todos os ocupantes do veículo","Apenas para passageiros no banco traseiro"],ans:2,exp:"O uso do cinto de segurança é obrigatório para TODOS os ocupantes do veículo em qualquer tipo de via."},
  {id:12,cat:"legislacao",text:"Qual documento comprova a propriedade do veículo?",opts:["IPVA quitado","CRV (DUT)","CRLV","Nota fiscal"],ans:1,exp:"O CRV (Certificado de Registro de Veículo), também conhecido como DUT, é o documento que comprova a propriedade do veículo."},
  {id:13,cat:"legislacao",text:"O condutor que se recusar ao teste do bafômetro estará sujeito a:",opts:["Apenas advertência","Multa leve","Mesma penalidade de embriaguez ao volante","Advertência e apreensão do veículo"],ans:2,exp:"A recusa ao teste do bafômetro implica as mesmas penalidades de dirigir embriagado, incluindo multa gravíssima e suspensão da CNH."},
  {id:14,cat:"sinais",text:"A placa circular vermelha com barra diagonal indica:",opts:["Velocidade máxima","Proibição de alguma ação","Regulamentação de sentido","Fim de restrição"],ans:1,exp:"Placas circulares vermelhas com barra diagonal são de proibição, indicando que a ação representada é proibida."},
  {id:15,cat:"sinais",text:"As placas triangulares com fundo amarelo são de:",opts:["Regulamentação","Advertência","Indicação","Serviços auxiliares"],ans:1,exp:"Placas triangulares com fundo amarelo (ou laranja em obras) são de advertência, alertando para situações que exigem atenção."},
  {id:16,cat:"sinais",text:"O semáforo com luz âmbar piscando indica:",opts:["Proibido passar","Atenção, reduza a velocidade","Pode passar normalmente","Cruzamento com preferência"],ans:1,exp:"Sinal âmbar piscante indica atenção redobrada. O condutor deve reduzir a velocidade e verificar se há pedestre ou veículo cruzando."},
  {id:17,cat:"sinais",text:"Qual é a cor das placas de indicação de sentido em rodovias federais?",opts:["Azul","Verde","Branco","Amarelo"],ans:1,exp:"Nas rodovias federais, as placas de indicação de sentido têm fundo verde. Fundo azul é usado em vias urbanas e rodovias estaduais."},
  {id:18,cat:"sinais",text:"A faixa contínua dupla amarela no centro da pista indica:",opts:["Pode ultrapassar nos dois sentidos","Proibida ultrapassagem nos dois sentidos","Pode ultrapassar apenas no sentido de quem vai","Fim de pista"],ans:1,exp:"A linha dupla contínua amarela proíbe a ultrapassagem em ambos os sentidos."},
  {id:19,cat:"sinais",text:"O que indica a placa com círculo azul e seta branca para o alto?",opts:["Sentido proibido","Via de mão única obrigatória","Ultrapassagem proibida","Velocidade mínima"],ans:1,exp:"Círculo azul com seta branca indica sentido obrigatório de circulação."},
  {id:20,cat:"sinais",text:"A placa de 'Pare' (STOP) é:",opts:["Quadrada vermelha","Octogonal vermelha","Triangular vermelha","Circular vermelha"],ans:1,exp:"A placa de STOP tem formato octogonal (oito lados) vermelha com letras brancas, e é única nesse formato justamente para fácil identificação."},
  {id:21,cat:"sinais",text:"Quando um agente de trânsito indica o braço levantado verticalmente, significa:",opts:["Parar","Seguir em frente","Atenção, cruzamento","Ultrapassagem permitida"],ans:0,exp:"Braço levantado verticalmente pelo agente significa PARAR para todos os que se aproximam do cruzamento."},
  {id:22,cat:"sinais",text:"O que significam as marcas em zigue-zague na pista?",opts:["Via em obras","Pista escorregadia","Área de faixa de pedestres ou redução de velocidade","Estacionamento proibido"],ans:2,exp:"Marcas em zigue-zague indicam proximidade de faixa de pedestres ou local de redução obrigatória de velocidade."},
  {id:23,cat:"sinais",text:"A linha tracejada branca longitudinal no centro da pista indica:",opts:["Proibido ultrapassar","Pode ultrapassar com segurança","Fim de pista","Estacionamento permitido"],ans:1,exp:"Linha tracejada no centro permite ultrapassagem quando há visibilidade e segurança suficientes."},
  {id:24,cat:"direcao",text:"O que é direção defensiva?",opts:["Dirigir lentamente sempre","Técnica para prevenir acidentes mesmo diante dos erros dos outros","Usar o freio frequentemente","Manter a janela fechada sempre"],ans:1,exp:"Direção defensiva é a técnica de condução que visa prevenir acidentes de trânsito, mesmo diante de erros dos outros motoristas ou condições adversas."},
  {id:25,cat:"direcao",text:"Qual a distância lateral mínima ao ultrapassar um ciclista?",opts:["0,5 metro","1 metro","1,5 metros","2 metros"],ans:2,exp:"A Lei do Ciclista (CTB, art. 58) determina distância lateral mínima de 1,5 metro ao ultrapassar ciclistas em vias urbanas, e 3 metros em rodovias."},
  {id:26,cat:"direcao",text:"Em situação de aquaplanagem, o que você deve fazer?",opts:["Frear bruscamente","Acelerar para sair da poça","Soltar o acelerador e manter o volante reto","Virar o volante para o lado"],ans:2,exp:"Em aquaplanagem, solte o acelerador suavemente, mantenha o volante firme e reto, e não freie bruscamente. Aguarde o controle retornar."},
  {id:27,cat:"direcao",text:"O que é 'ponto cego' de um veículo?",opts:["Área iluminada pelos faróis","Área não visível pelos espelhos retrovisores","Zona de sombra na estrada","Área de parada de emergência"],ans:1,exp:"Ponto cego é a área lateral do veículo que não é visível pelos espelhos retrovisores. Por isso, antes de mudar de faixa, é fundamental girar a cabeça para verificar."},
  {id:28,cat:"direcao",text:"Ao sentir sono ao volante, a melhor atitude é:",opts:["Abrir o vidro e ligar o ar condicionado","Tomar café e continuar","Parar em local seguro e descansar","Acelerar para chegar logo"],ans:2,exp:"A única medida eficaz contra o sono é parar e descansar. Café, ar frio e outros recursos são palitativos que podem gerar sensação falsa de alerta."},
  {id:29,cat:"direcao",text:"Qual é o tempo de reação médio de um motorista em condições normais?",opts:["0,5 segundo","0,75 segundo","1 segundo","1,5 segundo"],ans:1,exp:"O tempo médio de reação humana é de 0,75 segundo. A distância percorrida nesse tempo varia conforme a velocidade."},
  {id:30,cat:"direcao",text:"Ao passar por uma lombada em alta velocidade, o principal risco é:",opts:["Desgaste dos pneus","Dano na suspensão e perda de controle","Superaquecimento do motor","Consumo excessivo de combustível"],ans:1,exp:"Passar por lombadas em alta velocidade pode danificar a suspensão e causar perda momentânea do controle do veículo."},
  {id:31,cat:"alcool",text:"Qual é o limite legal de alcoolemia para dirigir no Brasil (Lei Seca)?",opts:["0,2 g/L","0,3 g/L","0,05 dg/L","Tolerância zero"],ans:3,exp:"A Lei Seca aplica a tolerância zero: qualquer concentração mensurável de álcool no sangue pode caracterizar infração. O limite considerado infração grave é 0,05 dg/L de sangue."},
  {id:32,cat:"alcool",text:"Dirigir sob influência de álcool com resultado de 0,34 mg/L ou mais no ar alveolar é considerado:",opts:["Infração grave","Infração gravíssima","Crime de trânsito","Infração leve"],ans:2,exp:"Concentrações iguais ou superiores a 0,34 mg/L de álcool no ar alveolar (ou 0,6 dg/L no sangue) configuram crime de trânsito previsto no art. 306 do CTB."},
  {id:33,cat:"alcool",text:"O álcool afeta principalmente qual função de um motorista?",opts:["Visão","Reflexos e coordenação motora","Audição","Força muscular"],ans:1,exp:"O álcool deteriora os reflexos, a coordenação motora, a capacidade de julgamento e a noção de risco — habilidades fundamentais para dirigir com segurança."},
  {id:34,cat:"alcool",text:"Qual é a penalidade para reincidência em embriaguez ao volante (crime)?",opts:["Multa dobrada","Pena de 3 a 6 anos de prisão","Suspensão imediata da CNH por 5 anos","Cassação definitiva da CNH"],ans:1,exp:"A reincidência no crime de embriaguez ao volante pode resultar em pena de 3 a 6 anos de reclusão, além de suspensão da habilitação."},
  {id:35,cat:"primeiros",text:"Ao encontrar um acidentado inconsciente, o que deve-se fazer PRIMEIRO?",opts:["Mover a vítima para local seguro imediatamente","Acionar o socorro (192/193) e sinalizar o local","Dar água à vítima","Fazer massagem cardíaca imediatamente"],ans:1,exp:"A prioridade é acionar o socorro profissional (SAMU 192 ou Bombeiros 193) e sinalizar o local para evitar novos acidentes. Mover a vítima pode agravar lesões."},
  {id:36,cat:"primeiros",text:"Quando é correto remover um acidentado do veículo?",opts:["Sempre, para facilitar os socorros","Somente se houver risco de incêndio ou afogamento","Quando o cinto de segurança estiver preso","Quando a ambulância ainda estiver longe"],ans:1,exp:"Só se deve remover a vítima do veículo em caso de risco iminente de incêndio ou afogamento, pois a remoção inadequada pode agravar lesões na coluna."},
  {id:37,cat:"primeiros",text:"O que é a manobra de RCP (Ressuscitação Cardiopulmonar)?",opts:["Procedimento para parar hemorragia","Técnica de respiração boca a boca apenas","Combinação de compressões torácicas e ventilações artificiais","Procedimento para desobstruir a via aérea"],ans:2,exp:"A RCP combina compressões torácicas (30) com ventilações (2) para manter o fluxo de sangue e oxigênio até a chegada dos profissionais de saúde."},
  {id:38,cat:"primeiros",text:"Como se deve proceder ao encontrar uma vítima com hemorragia externa grave?",opts:["Aplicar torniquete imediatamente","Comprimir o ferimento com pano limpo e manter a pressão","Lavar o ferimento com água","Elevar o ferimento acima da cabeça"],ans:1,exp:"A compressão direta com pano limpo sobre o ferimento é a forma mais eficaz de controlar hemorragia externa. O torniquete é última opção em casos extremos."},
  {id:39,cat:"meioambiente",text:"Qual alternativa de combustível contribui MENOS para emissões de CO2?",opts:["Gasolina comum","Diesel","Etanol","GNV"],ans:2,exp:"O etanol tem ciclo de carbono considerado mais neutro, pois o CO2 emitido foi absorvido pela cana durante seu crescimento. Emite menos GEE que gasolina ou diesel."},
  {id:40,cat:"meioambiente",text:"O que é a Inspeção Veicular Ambiental?",opts:["Multa por emissões","Verificação de ruídos do escapamento","Verificação periódica dos gases poluentes emitidos pelo veículo","Controle de derramamento de óleo"],ans:2,exp:"A inspeção veicular ambiental verifica se o veículo está dentro dos limites de emissão de poluentes e atende às normas do CONAMA."},
  {id:41,cat:"meioambiente",text:"O descarte incorreto de óleo de motor pode contaminar:",opts:["Apenas o solo","Apenas a água","Solo e água","Apenas o ar"],ans:2,exp:"Um litro de óleo usado pode contaminar até 1 milhão de litros de água. O descarte incorreto contamina solo e lençóis freáticos."},
  {id:42,cat:"legislacao",text:"Qual é a velocidade máxima em rodovias de pista dupla?",opts:["100 km/h","110 km/h","120 km/h","130 km/h"],ans:2,exp:"Em rodovias de pista dupla, a velocidade máxima é de 120 km/h para automóveis, conforme o CTB."},
  {id:43,cat:"legislacao",text:"Em vias urbanas, é permitido usar o celular enquanto dirige?",opts:["Sim, se viva-voz","Não, é infração gravíssima","Sim, parado no semáforo","Sim, se com fone de ouvido"],ans:1,exp:"O uso de celular enquanto dirige é infração gravíssima, mesmo com viva-voz ou fone, pois distrai a atenção do motorista."},
  {id:44,cat:"sinais",text:"O que indica uma placa com fundo marrom?",opts:["Obras na via","Pontos turísticos e de interesse cultural","Serviços de emergência","Rodovias federais"],ans:1,exp:"Placas com fundo marrom indicam atrativos turísticos, patrimônios históricos e pontos de interesse cultural."},
  {id:45,cat:"legislacao",text:"Quem tem preferência na ultrapassagem de ciclistas em cruzamentos?",opts:["O motorista sempre","O ciclista sempre","Quem chega primeiro","O veículo que vem pela direita"],ans:2,exp:"Em cruzamentos não sinalizados com ciclistas, aplica-se a regra geral: preferência para quem vem pela direita. Mas o motorista sempre deve ter cuidado redobrado."},
  {id:46,cat:"direcao",text:"O que se deve fazer ao perceber que os freios falharam?",opts:["Desligar o motor imediatamente","Puxar o freio de mão bruscamente","Reduzir marchas progressivamente e usar o freio de mão com cuidado","Acender o pisca-alerta e esperar"],ans:2,exp:"Em caso de falha de freio: mantenha a calma, reduz marchas progressivamente (motor freando), use o freio de mão suavemente e procure local seguro para parar."},
  {id:47,cat:"legislacao",text:"Qual é a multa mais grave no CTB (gravíssima com multiplicador)?",opts:["R$ 293,47","R$ 880,41","R$ 1.467,35","R$ 2.934,70"],ans:2,exp:"A multa gravíssima com fator multiplicador 5 (ex: racha) pode chegar a R$ 1.467,35 ou mais, dependendo da infração."},
  {id:48,cat:"sinais",text:"O que significa a placa com dois triângulos entrelaçados?",opts:["Cruzamento sinalizado","Entroncamento em 'Y'","Bifurcação","Retorno proibido"],ans:1,exp:"Dois triângulos entrelaçados indicam entroncamento em 'Y', alertando para o cruzamento em formato de 'Y' à frente."},
  {id:49,cat:"legislacao",text:"Crianças de até 7 anos e meio devem ser transportadas em:",opts:["Banco traseiro com cinto","Cadeirinha homologada no banco traseiro","Banco da frente com airbag","Qualquer posição com cinto"],ans:1,exp:"Crianças de até 7 anos e meio devem usar dispositivos de retenção (bebê conforto, cadeirinha ou assento) adequados ao peso e altura, instalados no banco traseiro."},
  {id:50,cat:"alcool",text:"Qual o tempo mínimo para que o álcool seja metabolizado pelo organismo?",opts:["30 minutos por dose","1 hora por dose","Varia por pessoa, não há tempo fixo","2 horas por dose"],ans:2,exp:"A metabolização do álcool varia conforme peso, sexo, alimentação, saúde do fígado etc. Não há tempo fixo — a única segurança é não beber e dirigir."}
];

const SINAIS_DATA = [
  {id:"r1",cat:"regulamentacao",name:"Velocidade máxima 60",desc:"Indica velocidade máxima permitida de 60 km/h naquela via. Placa de regulamentação circular.",tipo:"Regulamentação",svg:`<svg viewBox="0 0 70 70"><circle cx="35" cy="35" r="32" fill="#fff" stroke="#c0392b" stroke-width="5"/><text x="35" y="43" text-anchor="middle" font-size="18" font-weight="bold" fill="#222">60</text></svg>`},
  {id:"r2",cat:"regulamentacao",name:"Proibido estacionar",desc:"Proibido parar e estacionar o veículo naquele local.",tipo:"Regulamentação",svg:`<svg viewBox="0 0 70 70"><circle cx="35" cy="35" r="32" fill="#fff" stroke="#c0392b" stroke-width="5"/><text x="35" y="42" text-anchor="middle" font-size="22" font-weight="bold" fill="#222">E</text><line x1="12" y1="12" x2="58" y2="58" stroke="#c0392b" stroke-width="5"/></svg>`},
  {id:"r3",cat:"regulamentacao",name:"Sentido proibido",desc:"Proibida a entrada de veículos naquela via no sentido indicado.",tipo:"Regulamentação",svg:`<svg viewBox="0 0 70 70"><circle cx="35" cy="35" r="32" fill="#c0392b" stroke="#c0392b" stroke-width="2"/><rect x="14" y="29" width="42" height="12" rx="3" fill="#fff"/></svg>`},
  {id:"r4",cat:"regulamentacao",name:"Mão única à direita",desc:"Circulação obrigatória no sentido indicado pela seta.",tipo:"Regulamentação",svg:`<svg viewBox="0 0 70 70"><circle cx="35" cy="35" r="32" fill="#1a5fa6" stroke="#1a5fa6" stroke-width="2"/><polygon points="20,25 20,45 45,45 45,55 60,35 45,15 45,25" fill="#fff"/></svg>`},
  {id:"r5",cat:"regulamentacao",name:"Proibido ultrapassar",desc:"Não é permitido ultrapassar outros veículos naquele trecho.",tipo:"Regulamentação",svg:`<svg viewBox="0 0 70 70"><circle cx="35" cy="35" r="32" fill="#fff" stroke="#c0392b" stroke-width="5"/><circle cx="25" cy="35" r="8" fill="#888"/><circle cx="45" cy="35" r="8" fill="#c0392b"/><line x1="12" y1="12" x2="58" y2="58" stroke="#c0392b" stroke-width="5"/></svg>`},
  {id:"r6",cat:"regulamentacao",name:"Dê a preferência",desc:"O condutor deve dar a preferência de passagem ao outro fluxo de tráfego.",tipo:"Regulamentação",svg:`<svg viewBox="0 0 70 70"><polygon points="35,5 65,60 5,60" fill="#fff" stroke="#c0392b" stroke-width="4"/><polygon points="35,18 55,52 15,52" fill="#c0392b"/><text x="35" y="50" text-anchor="middle" font-size="13" font-weight="bold" fill="#fff">▼</text></svg>`},
  {id:"r7",cat:"regulamentacao",name:"Pare",desc:"Parada obrigatória. O condutor deve parar o veículo antes de avançar.",tipo:"Regulamentação",svg:`<svg viewBox="0 0 70 70"><polygon points="35,3 62,18 62,52 35,67 8,52 8,18" fill="#c0392b"/><text x="35" y="44" text-anchor="middle" font-size="16" font-weight="bold" fill="#fff">PARE</text></svg>`},
  {id:"r8",cat:"regulamentacao",name:"Proibido virar à esquerda",desc:"Proibida a conversão para a esquerda naquele ponto.",tipo:"Regulamentação",svg:`<svg viewBox="0 0 70 70"><circle cx="35" cy="35" r="32" fill="#fff" stroke="#c0392b" stroke-width="5"/><path d="M45 50 Q20 50 20 30 Q20 18 35 18" stroke="#222" stroke-width="4" fill="none"/><polygon points="35,10 27,22 43,22" fill="#222"/><line x1="12" y1="12" x2="58" y2="58" stroke="#c0392b" stroke-width="5"/></svg>`},
  {id:"a1",cat:"advertencia",name:"Curva à direita",desc:"Há uma curva perigosa à direita adiante. Reduza a velocidade.",tipo:"Advertência",svg:`<svg viewBox="0 0 70 70"><polygon points="35,5 65,60 5,60" fill="#f0c040" stroke="#888" stroke-width="2"/><path d="M30 45 Q30 30 45 25" stroke="#333" stroke-width="4" fill="none" stroke-linecap="round"/><polygon points="45,16 38,28 52,28" fill="#333"/></svg>`},
  {id:"a2",cat:"advertencia",name:"Pista escorregadia",desc:"Pista com baixa aderência, risco de derrapagem. Reduza a velocidade.",tipo:"Advertência",svg:`<svg viewBox="0 0 70 70"><polygon points="35,5 65,60 5,60" fill="#f0c040" stroke="#888" stroke-width="2"/><text x="35" y="52" text-anchor="middle" font-size="28">🌊</text></svg>`},
  {id:"a3",cat:"advertencia",name:"Passagem de pedestre",desc:"Há faixa de travessia de pedestres à frente. Atenção redobrada.",tipo:"Advertência",svg:`<svg viewBox="0 0 70 70"><polygon points="35,5 65,60 5,60" fill="#f0c040" stroke="#888" stroke-width="2"/><text x="35" y="52" text-anchor="middle" font-size="28">🚶</text></svg>`},
  {id:"a4",cat:"advertencia",name:"Animais na pista",desc:"Risco de animais cruzando a via. Reduza a velocidade.",tipo:"Advertência",svg:`<svg viewBox="0 0 70 70"><polygon points="35,5 65,60 5,60" fill="#f0c040" stroke="#888" stroke-width="2"/><text x="35" y="52" text-anchor="middle" font-size="28">🐄</text></svg>`},
  {id:"a5",cat:"advertencia",name:"Obras na via",desc:"Há obras adiante. Reduza velocidade e fique atento à sinalização.",tipo:"Advertência",svg:`<svg viewBox="0 0 70 70"><polygon points="35,5 65,60 5,60" fill="#f08010" stroke="#888" stroke-width="2"/><text x="35" y="52" text-anchor="middle" font-size="28">🚧</text></svg>`},
  {id:"a6",cat:"advertencia",name:"Cruzamento à frente",desc:"Há um cruzamento de vias à frente. Reduza e observe os lados.",tipo:"Advertência",svg:`<svg viewBox="0 0 70 70"><polygon points="35,5 65,60 5,60" fill="#f0c040" stroke="#888" stroke-width="2"/><line x1="35" y1="20" x2="35" y2="55" stroke="#333" stroke-width="4"/><line x1="22" y1="38" x2="48" y2="38" stroke="#333" stroke-width="4"/></svg>`},
  {id:"a7",cat:"advertencia",name:"Lombada",desc:"Há redutores de velocidade (lombada) adiante.",tipo:"Advertência",svg:`<svg viewBox="0 0 70 70"><polygon points="35,5 65,60 5,60" fill="#f0c040" stroke="#888" stroke-width="2"/><path d="M18 48 Q25 32 35 32 Q45 32 52 48" stroke="#333" stroke-width="4" fill="none"/></svg>`},
  {id:"a8",cat:"advertencia",name:"Escola",desc:"Área de escola próxima. Crianças podem cruzar a via. Máxima atenção.",tipo:"Advertência",svg:`<svg viewBox="0 0 70 70"><polygon points="35,5 65,60 5,60" fill="#f0c040" stroke="#888" stroke-width="2"/><text x="35" y="52" text-anchor="middle" font-size="28">🏫</text></svg>`},
  {id:"i1",cat:"indicacao",name:"Posto de gasolina",desc:"Indica posto de abastecimento de combustível nas proximidades.",tipo:"Indicação",svg:`<svg viewBox="0 0 70 70"><rect x="5" y="5" width="60" height="60" rx="6" fill="#1a5fa6"/><text x="35" y="42" text-anchor="middle" font-size="28">⛽</text></svg>`},
  {id:"i2",cat:"indicacao",name:"Hospital",desc:"Indica hospital ou pronto-socorro nas proximidades.",tipo:"Indicação",svg:`<svg viewBox="0 0 70 70"><rect x="5" y="5" width="60" height="60" rx="6" fill="#1a5fa6"/><text x="35" y="42" text-anchor="middle" font-size="28">🏥</text></svg>`},
  {id:"i3",cat:"indicacao",name:"Estacionamento",desc:"Indica área de estacionamento disponível.",tipo:"Indicação",svg:`<svg viewBox="0 0 70 70"><rect x="5" y="5" width="60" height="60" rx="6" fill="#1a5fa6"/><text x="35" y="48" text-anchor="middle" font-size="36" font-weight="bold" fill="#fff">P</text></svg>`},
  {id:"i4",cat:"indicacao",name:"Banheiro",desc:"Indica banheiro público nas proximidades.",tipo:"Indicação",svg:`<svg viewBox="0 0 70 70"><rect x="5" y="5" width="60" height="60" rx="6" fill="#1a5fa6"/><text x="35" y="42" text-anchor="middle" font-size="28">🚻</text></svg>`},
  {id:"i5",cat:"indicacao",name:"Aeroporto",desc:"Indica aeroporto nas proximidades.",tipo:"Indicação",svg:`<svg viewBox="0 0 70 70"><rect x="5" y="5" width="60" height="60" rx="6" fill="#1a5fa6"/><text x="35" y="42" text-anchor="middle" font-size="28">✈️</text></svg>`},
  {id:"s1",cat:"semaforo",name:"Sinal verde",desc:"Via liberada. O condutor pode prosseguir normalmente.",tipo:"Semáforo",svg:`<svg viewBox="0 0 70 70"><rect x="20" y="5" width="30" height="60" rx="6" fill="#333"/><circle cx="35" cy="18" r="9" fill="#555"/><circle cx="35" cy="35" r="9" fill="#555"/><circle cx="35" cy="52" r="9" fill="#27ae60"/></svg>`},
  {id:"s2",cat:"semaforo",name:"Sinal amarelo",desc:"Atenção: o sinal está mudando. Pare se seguro, prossiga com extremo cuidado.",tipo:"Semáforo",svg:`<svg viewBox="0 0 70 70"><rect x="20" y="5" width="30" height="60" rx="6" fill="#333"/><circle cx="35" cy="18" r="9" fill="#555"/><circle cx="35" cy="35" r="9" fill="#f0c040"/><circle cx="35" cy="52" r="9" fill="#555"/></svg>`},
  {id:"s3",cat:"semaforo",name:"Sinal vermelho",desc:"Via fechada. O condutor deve parar e aguardar.",tipo:"Semáforo",svg:`<svg viewBox="0 0 70 70"><rect x="20" y="5" width="30" height="60" rx="6" fill="#333"/><circle cx="35" cy="18" r="9" fill="#c0392b"/><circle cx="35" cy="35" r="9" fill="#555"/><circle cx="35" cy="52" r="9" fill="#555"/></svg>`},
  {id:"s4",cat:"semaforo",name:"Semáforo amarelo piscante",desc:"Atenção redobrada. O condutor deve reduzir velocidade e verificar a via antes de cruzar.",tipo:"Semáforo",svg:`<svg viewBox="0 0 70 70"><rect x="20" y="8" width="30" height="54" rx="6" fill="#333"/><circle cx="35" cy="35" r="12" fill="#f0c040" opacity="0.9"/><text x="35" y="42" text-anchor="middle" font-size="18" fill="#333">!</text></svg>`},
  {id:"s5",cat:"semaforo",name:"Semáforo pedestre — pare",desc:"Pedestres devem aguardar na calçada. Não atravessar.",tipo:"Semáforo",svg:`<svg viewBox="0 0 70 70"><rect x="20" y="5" width="30" height="60" rx="6" fill="#333"/><circle cx="35" cy="20" r="10" fill="#c0392b"/><text x="35" y="52" text-anchor="middle" font-size="28" fill="#c0392b">✋</text></svg>`},
  {id:"s6",cat:"semaforo",name:"Semáforo pedestre — ande",desc:"Pedestres podem atravessar com segurança.",tipo:"Semáforo",svg:`<svg viewBox="0 0 70 70"><rect x="20" y="5" width="30" height="60" rx="6" fill="#333"/><circle cx="35" cy="20" r="10" fill="#555"/><text x="35" y="54" text-anchor="middle" font-size="28" fill="#27ae60">🚶</text></svg>`},
  {id:"g1",cat:"gestos",name:"Braço levantado — pare",desc:"Agente com braço erguido verticalmente. Todos os veículos devem parar.",tipo:"Gesto",svg:`<svg viewBox="0 0 70 70"><circle cx="35" cy="14" r="8" fill="#f5cba7"/><rect x="29" y="22" width="12" height="22" rx="4" fill="#1a5fa6"/><line x1="35" y1="30" x2="50" y2="18" stroke="#f5cba7" stroke-width="5" stroke-linecap="round"/><rect x="28" y="44" width="6" height="16" rx="3" fill="#333"/><rect x="36" y="44" width="6" height="16" rx="3" fill="#333"/></svg>`},
  {id:"g2",cat:"gestos",name:"Braço horizontal — siga",desc:"Agente com braço estendido horizontalmente. Os veículos no sentido perpendicular podem passar.",tipo:"Gesto",svg:`<svg viewBox="0 0 70 70"><circle cx="35" cy="14" r="8" fill="#f5cba7"/><rect x="29" y="22" width="12" height="22" rx="4" fill="#1a5fa6"/><line x1="12" y1="30" x2="58" y2="30" stroke="#f5cba7" stroke-width="5" stroke-linecap="round"/><rect x="28" y="44" width="6" height="16" rx="3" fill="#333"/><rect x="36" y="44" width="6" height="16" rx="3" fill="#333"/></svg>`},
  {id:"h1",cat:"horizontal",name:"Faixa de pedestre",desc:"Indica local de travessia de pedestres. O motorista deve dar preferência ao pedestre.",tipo:"Marca horizontal",svg:`<svg viewBox="0 0 70 70"><rect x="5" y="5" width="60" height="60" rx="4" fill="#e8e8e8"/><rect x="10" y="15" width="50" height="8" fill="#fff" stroke="#999" stroke-width="0.5"/><rect x="10" y="27" width="50" height="8" fill="#fff" stroke="#999" stroke-width="0.5"/><rect x="10" y="39" width="50" height="8" fill="#fff" stroke="#999" stroke-width="0.5"/><rect x="10" y="51" width="50" height="8" fill="#fff" stroke="#999" stroke-width="0.5"/></svg>`},
  {id:"h2",cat:"horizontal",name:"Linha central contínua",desc:"Proíbe a ultrapassagem em ambos os sentidos. Não ultrapasse nem invada a faixa oposta.",tipo:"Marca horizontal",svg:`<svg viewBox="0 0 70 70"><rect x="5" y="5" width="60" height="60" rx="4" fill="#444"/><line x1="5" y1="32" x2="65" y2="32" stroke="#f0c040" stroke-width="3"/><line x1="5" y1="38" x2="65" y2="38" stroke="#f0c040" stroke-width="3"/></svg>`},
  {id:"h3",cat:"horizontal",name:"Linha tracejada",desc:"Permite ultrapassagem quando há segurança e visibilidade adequadas.",tipo:"Marca horizontal",svg:`<svg viewBox="0 0 70 70"><rect x="5" y="5" width="60" height="60" rx="4" fill="#444"/><line x1="5" y1="35" x2="20" y2="35" stroke="#fff" stroke-width="3"/><line x1="27" y1="35" x2="43" y2="35" stroke="#fff" stroke-width="3"/><line x1="50" y1="35" x2="65" y2="35" stroke="#fff" stroke-width="3"/></svg>`},
  {id:"h4",cat:"horizontal",name:"Linha de retenção (PARE)",desc:"Indica o local exato onde o veículo deve parar no sinal ou placa STOP.",tipo:"Marca horizontal",svg:`<svg viewBox="0 0 70 70"><rect x="5" y="5" width="60" height="60" rx="4" fill="#444"/><line x1="5" y1="40" x2="65" y2="40" stroke="#fff" stroke-width="5"/><text x="35" y="32" text-anchor="middle" font-size="11" fill="#f0c040" font-weight="bold">PARE</text></svg>`},
  {id:"h5",cat:"horizontal",name:"Zigue-zague",desc:"Alerta para faixa de pedestres ou redução de velocidade obrigatória próxima.",tipo:"Marca horizontal",svg:`<svg viewBox="0 0 70 70"><rect x="5" y="5" width="60" height="60" rx="4" fill="#444"/><polyline points="10,50 18,25 26,50 34,25 42,50 50,25 60,50" stroke="#f0c040" stroke-width="3" fill="none"/></svg>`}
];

const DICAS = [
  {icon:"ti-road",title:"Macete das placas por forma",text:"Círculo = obrigação/proibição. Triângulo = advertência. Retângulo = indicação. Octógono = PARE. Associe a forma ao significado antes de decorar cada placa!"},
  {icon:"ti-traffic-lights",title:"Semáforo: V-A-V",text:"Verde = pode ir. Amarelo = atenção (NÃO acelere!). Vermelho = pare. Quando amarelo, só passe se já estiver no cruzamento. Nunca acelere ao ver o amarelo."},
  {icon:"ti-beer",title:"Lei Seca — tolerância zero",text:"'Bebeu, não dirija' não é apenas conselho — é lei. Qualquer concentração mensurável pode configurar infração. A recusa ao bafômetro tem a mesma penalidade."},
  {icon:"ti-seatbelt",title:"Cinto para TODOS",text:"O motorista é responsável pelo uso do cinto de todos os ocupantes. Criança até 7,5 anos: cadeirinha adequada. Multa + pontos para o motorista por criança sem dispositivo."},
  {icon:"ti-car",title:"Distância segura = tempo de reação",text:"A cada 10 km/h de velocidade, você percorre cerca de 3 metros durante o tempo de reação (0,75s). A 60 km/h = ~12 metros antes de sequer pisar no freio!"},
  {icon:"ti-arrow-right",title:"Direita tem preferência",text:"Em cruzamentos não sinalizados, dê a preferência a quem vem pela sua direita. É a regra mais básica e mais cobrada nas provas!"},
  {icon:"ti-line",title:"Linhas no asfalto",text:"Linha branca = divide sentidos iguais ou delimita faixas. Linha amarela = divide sentidos opostos. Contínua = não ultrapasse. Tracejada = pode ultrapassar."},
  {icon:"ti-first-aid-kit",title:"Acidente — o que fazer",text:"1) Sinalize o local (triângulo 30m). 2) Ligue para SAMU (192) ou Bombeiros (193). 3) NÃO mova a vítima (a não ser risco de incêndio). 4) Preste primeiros socorros se souber."},
  {icon:"ti-phone-off",title:"Celular ao volante = crime",text:"Usar celular dirigindo: multa gravíssima + 7 pontos na CNH. Não há exceção — nem em sinal vermelho, nem com fone, nem com viva-voz. Largue o celular!"},
  {icon:"ti-clock",title:"Velocidades máximas — decoreba",text:"Via rural de pista simples: 100 km/h. Via rural de pista dupla: 120 km/h. Via urbana: 60 km/h. Via expressa urbana: 80 km/h. Vias locais: 30 km/h."}
];

async function seedTable(tableName, items) {
  console.log(`Populando tabela ${tableName}...`);
  try {
    // 1. Apagar dados antigos para evitar duplicatas ao re-rodar
    const deleteRes = await fetch(`${supabaseUrl}/rest/v1/${tableName}`, {
      method: 'DELETE',
      headers: {
        'apikey': serviceKey,
        'Authorization': `Bearer ${serviceKey}`
      }
    });
    
    if (deleteRes.status >= 300) {
      console.warn(`Aviso ao limpar ${tableName}: Status ${deleteRes.status}`);
    }

    // 2. Inserir dados
    const insertRes = await fetch(`${supabaseUrl}/rest/v1/${tableName}`, {
      method: 'POST',
      headers: {
        'apikey': serviceKey,
        'Authorization': `Bearer ${serviceKey}`,
        'Content-Type': 'application/json',
        'Prefer': 'resolution=merge-duplicates'
      },
      body: JSON.stringify(items)
    });

    if (insertRes.status === 201 || insertRes.status === 200) {
      console.log(`Tabela ${tableName} populada com sucesso! (${items.length} itens)`);
    } else {
      const err = await insertRes.text();
      console.error(`Erro ao popular ${tableName}: Status ${insertRes.status} -`, err);
    }
  } catch (err) {
    console.error(`Erro na requisição da tabela ${tableName}:`, err);
  }
}

async function run() {
  await seedTable('questions', QUESTIONS);
  await seedTable('sinais_data', SINAIS_DATA);
  await seedTable('dicas', DICAS);
  console.log('Operação de seed finalizada.');
}

run();
